name: Draft release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # https://github.com/actions/upload-artifact/issues/21#issuecomment-2393490651
      - name: Download successful build artifacts for this commit
        run: |
          gh_last_success_run_id=$(gh run list -w $WORKFLOW --branch $BRANCH --commit $COMMIT --json conclusion,databaseId --jq 'first(.[] | select(.conclusion == "success")) | .databaseId')
          [ -z "$gh_last_success_run_id" ] && echo "No successful run found" && exit 1 || true
          gh run download $gh_last_success_run_id -D $OUTPUT_DIR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: .github/workflows/build.yml
          OUTPUT_DIR: artifacts
          BRANCH: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}

      - name: Rename artifacts
        run: |
          mkdir -p renamed_artifacts

          for artifact_dir in artifacts/*/; do
            base_name=$(basename "$artifact_dir")
            
            # Determine the new filename based on the artifact name
            case "$base_name" in
              "acord-aarch64-apple-darwin-dmg")
                new_name="Acord_${{ inputs.version }}_aarch64.dmg"
                ;;
              "acord-aarch64-pc-windows-msvc-nsis")
                new_name="Acord_${{ inputs.version }}.arm64-setup.exe"
                ;;
              "acord-aarch64-pc-windows-msvc-portable")
                new_name="Acord_${{ inputs.version }}_win_arm64_portable.zip"
                ;;
              "acord-aarch64-unknown-linux-gnu-deb")
                new_name="Acord_${{ inputs.version }}_arm64.deb"
                ;;
              "acord-aarch64-unknown-linux-gnu-portable")
                new_name="Acord_${{ inputs.version }}_arm64_portable.tar.gz"
                ;;
              "acord-aarch64-unknown-linux-gnu-rpm")
                new_name="Acord_${{ inputs.version }}-1.aarch64.rpm"
                ;;
              "acord-armv7-unknown-linux-gnueabihf-deb")
                new_name="Acord_${{ inputs.version }}_armhf.deb"
                ;;
              "acord-armv7-unknown-linux-gnueabihf-portable")
                new_name="Acord_${{ inputs.version }}_armv7_portable.tar.gz"
                ;;
              "acord-armv7-unknown-linux-gnueabihf-rpm")
                new_name="Acord_${{ inputs.version }}-1.armhfp.rpm"
                ;;
              "acord-x86_64-apple-darwin-dmg")
                new_name="Acord_${{ inputs.version }}_x64.dmg"
                ;;
              "acord-x86_64-pc-windows-msvc-nsis")
                new_name="Acord_${{ inputs.version }}_x64-setup.exe"
                ;;
              "acord-x86_64-pc-windows-msvc-msi")
                new_name="Acord_${{ inputs.version }}_x64_en-US.msi"
                ;;
              "acord-x86_64-pc-windows-msvc-portable")
                new_name="Acord_${{ inputs.version }}_win64_portable.zip"
                ;;
              "acord-x86_64-unknown-linux-gnu-appimage")
                new_name="Acord_${{ inputs.version }}_amd64.AppImage"
                ;;
              "acord-x86_64-unknown-linux-gnu-deb")
                new_name="Acord_${{ inputs.version }}_amd64.deb"
                ;;
              "acord-x86_64-unknown-linux-gnu-portable")
                new_name="Acord_${{ inputs.version }}_amd64_portable.tar.gz"
                ;;
              "acord-x86_64-unknown-linux-gnu-rpm")
                new_name="Acord_${{ inputs.version }}-1.x86_64.rpm"
                ;;
              *)
                # Skip unknown artifacts
                continue
                ;;
            esac

            # Find the actual artifact file in the directory (assuming there's only one file)
            artifact_file=$(find "$artifact_dir" -type f -print -quit)
            
            if [ -n "$artifact_file" ]; then
              echo "Renaming $artifact_file to $new_name"
              # Copy and rename the file
              cp "$artifact_file" "renamed_artifacts/$new_name"
            fi
          done

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          body: "If you can see this, I forgot to change the release description."
          files: renamed_artifacts/*
          draft: true
